apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer
